name: ayulin.net
markdown: redcarpet
pygments: false
source: Content
destination: Build

permalink: /blog/:year/:month/:day/:title.html

# Pagination
paginate: 10
paginate_path: "blog/page:num"

# RSS Feed
url: http://ayulin.net/blog
author: Ayulin
rss_path: blog/