name: ayulin.net
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
highlighter: rouge
source: ./Content
timezone: Asia/Singapore
encoding: utf-8

permalink: /blog/:year/:title/

# Pagination
paginate_path: "/blog/page:num"
paginate: 7

# RSS Feed
url: http://ayulin.net/blog
author: Ayulin
