name: ayulin.net
markdown: redcarpet
pygments: false
source: Content
destination: Build

permalink: /blog/:year/:month/:day/:title.html

# Pagination
paginate: 7
paginate_path: "blog/page:num"

# RSS Feed
url: http://ayulin.net
author: Ayulin
rss_path: blog/
rss_post_limit: 10